// Command omni-helm-chart-gen generates the Omni Helm chart reference page
// from the chart README.
//
// The README in the Omni repository is the source of truth for the chart. This
// tool copies it into the docs site and converts the GitHub-flavored Markdown
// that Mintlify cannot render as MDX:
//
//   - drops the H1, the version badges, the homepage line, and the Maintainers
//     section (the page title and the site cover these)
//   - converts GitHub alerts (> [!NOTE], > [!WARNING], ...) to Mintlify callouts
//   - converts bare autolinks (<https://...>, <user@example.com>) to Markdown
//     links, since MDX parses a bare < as JSX
//   - rewrites relative links (values.yaml) to the chart directory on GitHub
//
// The page is written to stdout.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
	"time"
)

const (
	latestReleaseURL = "https://api.github.com/repos/siderolabs/omni/releases/latest"
	readmeURLFormat  = "https://raw.githubusercontent.com/siderolabs/omni/%s/deploy/helm/omni/README.md"
	chartURLFormat   = "https://github.com/siderolabs/omni/blob/%s/deploy/helm/omni"

	pageTitle       = "Omni Helm Chart"
	pageDescription = "Install and configure Omni on Kubernetes with the Omni Helm chart."
)

func main() {
	readmePath := flag.String("readme", "", "read the README from this local file instead of fetching it (the ref is still used for links)")

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: %s [-readme path] [omni-ref]\n\n", os.Args[0])
		fmt.Fprintln(os.Stderr, "omni-ref is a tag or branch of siderolabs/omni. It defaults to the latest")
		fmt.Fprintln(os.Stderr, "Omni release, so the page matches the chart published to ghcr.io.")
		flag.PrintDefaults()
	}

	flag.Parse()

	if err := run(flag.Arg(0), *readmePath, os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run(ref, readmePath string, out io.Writer) error {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	var err error

	if ref == "" {
		if ref, err = latestRelease(ctx); err != nil {
			return fmt.Errorf("resolving the latest Omni release: %w", err)
		}
	}

	var readme []byte

	if readmePath != "" {
		readme, err = os.ReadFile(readmePath)
	} else {
		readme, err = fetch(ctx, fmt.Sprintf(readmeURLFormat, ref))
	}

	if err != nil {
		return fmt.Errorf("reading the chart README: %w", err)
	}

	_, err = io.WriteString(out, convert(string(readme), ref))

	return err
}

func latestRelease(ctx context.Context) (string, error) {
	body, err := fetch(ctx, latestReleaseURL)
	if err != nil {
		return "", err
	}

	var release struct {
		TagName string `json:"tag_name"`
	}

	if err := json.Unmarshal(body, &release); err != nil {
		return "", err
	}

	if release.TagName == "" {
		return "", errors.New("no tag_name in the GitHub response")
	}

	return release.TagName, nil
}

func fetch(ctx context.Context, url string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close() //nolint:errcheck

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: %s", url, resp.Status)
	}

	return io.ReadAll(resp.Body)
}

var (
	fenceRe    = regexp.MustCompile("^\\s*```")
	alertRe    = regexp.MustCompile(`^> \[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*$`)
	urlLinkRe  = regexp.MustCompile(`<(https?://[^\s>]+)>`)
	mailLinkRe = regexp.MustCompile(`<([^\s<>@]+@[^\s<>]+)>`)

	// Mintlify has no Important or Caution callout; map them to the closest.
	callouts = map[string]string{
		"NOTE":      "Note",
		"TIP":       "Tip",
		"IMPORTANT": "Info",
		"WARNING":   "Warning",
		"CAUTION":   "Warning",
	}
)

// convert turns the chart README into the MDX reference page.
func convert(readme, ref string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "---\ntitle: %s\ndescription: %s\n---\n\n", pageTitle, pageDescription)
	fmt.Fprintf(&b, "{/* This file is automatically generated from the Omni Helm chart README (%s). "+
		"Do not edit manually; run make generate-omni-helm-chart-reference. */}\n\n", ref)

	valuesURL := fmt.Sprintf(chartURLFormat, ref) + "/values.yaml"

	var (
		inFence   bool
		inSkip    bool   // inside the dropped Maintainers section
		callout   string // open Mintlify callout, if any
		lastBlank = true // drops leading blank lines, and collapses runs of them
	)

	emit := func(line string) {
		blank := strings.TrimSpace(line) == ""
		if blank && lastBlank {
			return
		}

		b.WriteString(line)
		b.WriteByte('\n')

		lastBlank = blank
	}

	closeCallout := func() {
		if callout != "" {
			emit("</" + callout + ">")
			callout = ""
		}
	}

	lines := strings.Split(strings.ReplaceAll(readme, "\r\n", "\n"), "\n")

	for i, line := range lines {
		if fenceRe.MatchString(line) {
			closeCallout()
			inFence = !inFence
			// Always keep a fence line, and never collapse the blank after it.
			b.WriteString(line)
			b.WriteByte('\n')
			lastBlank = false

			continue
		}

		if inFence {
			b.WriteString(line)
			b.WriteByte('\n')

			continue
		}

		switch {
		case i == 0 && strings.HasPrefix(line, "# "):
			continue
		case strings.Contains(line, "img.shields.io"):
			continue
		case strings.HasPrefix(line, "**Homepage:**"):
			continue
		case strings.HasPrefix(line, "## Maintainers"):
			inSkip = true

			continue
		case inSkip && strings.HasPrefix(line, "## "):
			inSkip = false
		case inSkip:
			continue
		}

		if m := alertRe.FindStringSubmatch(line); m != nil {
			closeCallout()
			callout = callouts[m[1]]
			emit("<" + callout + ">")

			continue
		}

		// Inside a callout, strip the quote marker; the first unquoted line ends it.
		if callout != "" {
			if strings.HasPrefix(line, ">") {
				line = strings.TrimPrefix(strings.TrimPrefix(line, ">"), " ")
			} else {
				closeCallout()
			}
		}

		line = urlLinkRe.ReplaceAllString(line, "[$1]($1)")
		line = mailLinkRe.ReplaceAllString(line, "[$1](mailto:$1)")
		line = strings.ReplaceAll(line, "](values.yaml)", "]("+valuesURL+")")

		emit(line)
	}

	closeCallout()

	return strings.TrimRight(b.String(), "\n") + "\n"
}
