package main

import (
	"strings"
	"testing"
)

// run normalizes with escaping OFF (the default for structural-only passes).
func run(t *testing.T, in string, stripHR bool) string {
	t.Helper()
	return strings.Join(normalize(strings.Split(in, "\n"), stripHR, false), "\n")
}

// runEsc normalizes with escaping ON (as used for plain-markdown CLI help).
func runEsc(t *testing.T, in string, stripHR bool) string {
	t.Helper()
	return strings.Join(normalize(strings.Split(in, "\n"), stripHR, true), "\n")
}

func TestColonIntroBecomesFencedCode(t *testing.T) {
	in := "To load completions in your current shell session:\n\n\tsource <(omnictl completion bash)\n\nnext paragraph\n"
	want := "To load completions in your current shell session:\n\n```\nsource <(omnictl completion bash)\n```\n\nnext paragraph\n"
	if got := run(t, in, false); got != want {
		t.Errorf("colon intro not fenced:\n got: %q\nwant: %q", got, want)
	}
}

func TestHeadingColonIntroBecomesFencedCode(t *testing.T) {
	// A command example without any MDX-breaking characters must still be
	// fenced when introduced by a colon (here a "#### Linux:" heading).
	in := "#### Linux:\n\n\tomnictl completion bash > /etc/bash_completion.d/omnictl\n"
	want := "#### Linux:\n\n```\nomnictl completion bash > /etc/bash_completion.d/omnictl\n```\n"
	if got := run(t, in, false); got != want {
		t.Errorf("heading-colon intro not fenced:\n got: %q\nwant: %q", got, want)
	}
}

func TestSentenceIntroBecomesProse(t *testing.T) {
	in := "Create or update resources using YAML file(s) as input.\n\n\tIf a file is specified, only that file will be processed.\n\tIf a directory is specified, all files are processed.\n"
	want := "Create or update resources using YAML file(s) as input.\n\nIf a file is specified, only that file will be processed.\nIf a directory is specified, all files are processed.\n"
	if got := run(t, in, false); got != want {
		t.Errorf("prose block not de-indented:\n got: %q\nwant: %q", got, want)
	}
}

// TestNestedListNotFenced covers a list nested under a list item ("- For each
// node:"): it must stay a list, indented, not become a fenced code block.
func TestNestedListNotFenced(t *testing.T) {
	in := "- For each node:\n\n\t- Kernel logs.\n\t- Talos version.\n- For the cluster:\n\n\t- Manifests.\n"
	want := "- For each node:\n\n  - Kernel logs.\n  - Talos version.\n- For the cluster:\n\n  - Manifests.\n"
	if got := run(t, in, false); got != want {
		t.Errorf("nested list was fenced or flattened:\n got: %q\nwant: %q", got, want)
	}
}

// TestNestedListEscapesContent: with --escape-inline, a placeholder inside a
// nested list item must be escaped (like any other prose) and the pass must be
// idempotent — the nested-list branch previously skipped escaping.
func TestNestedListEscapesContent(t *testing.T) {
	in := "- Steps:\n\n\t- see <machine-id>\n"
	want := "- Steps:\n\n  - see \\<machine-id>\n"
	once := runEsc(t, in, false)
	if once != want {
		t.Errorf("nested list content not escaped:\n got: %q\nwant: %q", once, want)
	}
	twice := strings.Join(normalize(strings.Split(once, "\n"), false, true), "\n")
	if once != twice {
		t.Errorf("nested list escape not idempotent:\n once: %q\ntwice: %q", once, twice)
	}
}

func TestExistingFenceUntouched(t *testing.T) {
	// A tab-indented line inside a real fenced block must not be re-fenced.
	in := "```bash\n\tsource <(cmd)\n```\n"
	if got := run(t, in, false); got != in {
		t.Errorf("existing fenced block altered:\n got: %q\nwant: %q", got, in)
	}
}

// TestHTMLTablePreserved is the key safety test: files with real HTML/JSX (the
// Talos config reference, schema-generated Omni pages) must pass through
// untouched when escaping is off — escaping would corrupt "<table>" into
// "\<table>".
func TestHTMLTablePreserved(t *testing.T) {
	in := "AddressConfig represents a network address configuration.\n\n<table>\n  <thead>\n    <tr>\n      <th>Field</th>\n    </tr>\n  </thead>\n</table>\n"
	if got := run(t, in, false); got != in {
		t.Errorf("HTML table altered with escaping off:\n got: %q\nwant: %q", got, in)
	}
}

// TestMDXExpressionsPreserved: with escaping off (the path used for HTML-bearing
// reference pages), {"<"} / {">"} JSX expressions and {/* */} comments must pass
// through untouched. This is the guarantee that protects the Talos reference.
func TestMDXExpressionsPreserved(t *testing.T) {
	in := "{/*\nThis file is automatically generated.\n*/}\n\nCreates an archive at {\"<\"}src-path{\">\"} now.\n"
	if got := run(t, in, false); got != in {
		t.Errorf("MDX expressions altered with escaping off:\n got: %q\nwant: %q", got, in)
	}
}

// TestEscapeInlineEscapesBraceExpressions locks in that --escape-inline escapes
// expression-looking prose too. These files are plain-markdown CLI help with no
// intentional JSX, so an unescaped "{" (e.g. a JSON default like {"cni":"x"})
// would break the MDX build.
func TestEscapeInlineEscapesBraceExpressions(t *testing.T) {
	in := "default is (cni {\"name\":\"flannel\"}) and path {/etc}\n"
	want := "default is (cni \\{\"name\":\"flannel\"}) and path \\{/etc}\n"
	if got := runEsc(t, in, false); got != want {
		t.Errorf("brace expression not escaped:\n got: %q\nwant: %q", got, want)
	}
}

func TestFrontmatterPreserved(t *testing.T) {
	// Closing delimiter has a trailing space, and strip-hr is on: the
	// frontmatter must survive intact.
	in := "---\ntitle: Image Factory Configuration\ndescription: something\n--- \n\n## CLI Usage\n"
	want := in
	if got := run(t, in, true); got != want {
		t.Errorf("frontmatter not preserved:\n got: %q\nwant: %q", got, want)
	}
}

func TestStripHR(t *testing.T) {
	in := "HTTP configuration.\n\n---\n\n### `http.httpListenAddr`\n"
	want := "HTTP configuration.\n\n### `http.httpListenAddr`\n"
	if got := run(t, in, true); got != want {
		t.Errorf("HR not stripped:\n got: %q\nwant: %q", got, want)
	}
}

func TestStripHRDisabledByDefault(t *testing.T) {
	in := "a\n\n---\n\nb\n"
	if got := run(t, in, false); got != in {
		t.Errorf("HR stripped without --strip-hr:\n got: %q\nwant: %q", got, in)
	}
}

// Escaping is opt-in: with it off, "<machine-id>" in prose is left as-is.
func TestNoEscapeByDefault(t *testing.T) {
	in := "use 'omnictl get machinestatus <machine-id> -o yaml' to inspect it\n"
	if got := run(t, in, false); got != in {
		t.Errorf("prose escaped with escaping off:\n got: %q\nwant: %q", got, in)
	}
}

func TestEscapesInlinePlaceholderInProse(t *testing.T) {
	in := "use 'omnictl get machinestatus <machine-id> -o yaml' to inspect it\n"
	want := "use 'omnictl get machinestatus \\<machine-id> -o yaml' to inspect it\n"
	if got := runEsc(t, in, false); got != want {
		t.Errorf("inline < not escaped:\n got: %q\nwant: %q", got, want)
	}
}

func TestDoesNotEscapeInsideFencedCode(t *testing.T) {
	in := "```\nomnictl get machinestatus <machine-id>\n```\n"
	if got := runEsc(t, in, false); got != in {
		t.Errorf("escaped inside fenced code:\n got: %q\nwant: %q", got, in)
	}
}

func TestDoesNotEscapeInsideInlineCodeSpan(t *testing.T) {
	in := "run `omnictl get machinestatus <machine-id>` now\n"
	if got := runEsc(t, in, false); got != in {
		t.Errorf("escaped inside inline code span:\n got: %q\nwant: %q", got, in)
	}
}

func TestEscapesBraceInProse(t *testing.T) {
	in := "the value {placeholder} is required\n"
	want := "the value \\{placeholder} is required\n"
	if got := runEsc(t, in, false); got != want {
		t.Errorf("inline { not escaped:\n got: %q\nwant: %q", got, want)
	}
}

// Escaping must not double-escape its own output.
func TestEscapeInlineIdempotent(t *testing.T) {
	in := "use <machine-id> and {placeholder} and (cni {\"a\":\"b\"})\n"
	once := runEsc(t, in, false)
	twice := strings.Join(normalize(strings.Split(once, "\n"), false, true), "\n")
	if once != twice {
		t.Errorf("escape pass not idempotent:\n once: %q\ntwice: %q", once, twice)
	}
	if strings.Contains(once, "\\\\") {
		t.Errorf("double-escaped:\n got: %q", once)
	}
}

// TestNestedListDeeperLevels: a two-level tab-indented list must keep its
// nesting (two spaces per original tab), not end up with mixed tabs and spaces.
func TestNestedListDeeperLevels(t *testing.T) {
	in := "- Top:\n\n\t- One.\n\t\t- Two.\n"
	want := "- Top:\n\n  - One.\n    - Two.\n"
	if got := run(t, in, false); got != want {
		t.Errorf("deeper nesting not preserved:\n got: %q\nwant: %q", got, want)
	}
}

func TestStripHRKeepsFencedSeparators(t *testing.T) {
	// A "---" inside a code block (e.g. a YAML document separator) must stay.
	in := "```yaml\nfoo: 1\n---\nbar: 2\n```\n"
	if got := run(t, in, true); got != in {
		t.Errorf("fenced --- was stripped:\n got: %q\nwant: %q", got, in)
	}
}

// TestIdempotent runs a representative document twice through normalize and
// checks the second pass is a no-op, for both flag combinations.
func TestIdempotent(t *testing.T) {
	docs := []string{
		"To load completions:\n\n\tsource <(talosctl completion bash)\n",
		"- For each node:\n\n\t- Kernel logs.\n",
		"<table>\n  <tr>\n    <td>x</td>\n  </tr>\n</table>\n",
		"{/*\ngenerated\n*/}\n\nuse {\"<\"}id{\">\"} here\n",
	}
	for _, escape := range []bool{false, true} {
		for _, in := range docs {
			once := strings.Join(normalize(strings.Split(in, "\n"), false, escape), "\n")
			twice := strings.Join(normalize(strings.Split(once, "\n"), false, escape), "\n")
			if once != twice {
				t.Errorf("not idempotent (escape=%v):\n in:   %q\n once: %q\n twice:%q", escape, in, once, twice)
			}
		}
	}
}

// TestUnpairedBacktickStillEscapes covers CLI help with an odd number of
// backticks on a line: the stray backtick is not a code span, so escaping must
// continue past it rather than leaving a bare "<machine-id>" in the output.
func TestUnpairedBacktickStillEscapes(t *testing.T) {
	in := "use `omnictl and then <machine-id> is required\n"
	want := "use `omnictl and then \\<machine-id> is required\n"
	once := runEsc(t, in, false)
	if once != want {
		t.Errorf("unpaired backtick disabled escaping:\n got: %q\nwant: %q", once, want)
	}
	twice := strings.Join(normalize(strings.Split(once, "\n"), false, true), "\n")
	if once != twice {
		t.Errorf("unpaired-backtick escape not idempotent:\n once: %q\ntwice: %q", once, twice)
	}
	// A balanced pair still protects its contents.
	bal := "run `omnictl get <id>` for <machine-id>\n"
	wantBal := "run `omnictl get <id>` for \\<machine-id>\n"
	if got := runEsc(t, bal, false); got != wantBal {
		t.Errorf("balanced code span not respected:\n got: %q\nwant: %q", got, wantBal)
	}
}

// TestTabIndentedFenceNotDoubleFenced covers a tab-indented fenced block under
// a colon intro. fenceRe only matches space-indented fences, so the block falls
// into the tab-block branch; it must not be wrapped in a second fence, and the
// pass must be idempotent.
func TestTabIndentedFenceNotDoubleFenced(t *testing.T) {
	in := "For example:\n\n\t```bash\n\tomnictl get machines\n\t```\n"
	want := "For example:\n\n```bash\nomnictl get machines\n```\n"
	once := run(t, in, false)
	if once != want {
		t.Errorf("tab-indented fence mangled:\n got: %q\nwant: %q", once, want)
	}
	if twice := run(t, once, false); once != twice {
		t.Errorf("tab-indented fence not idempotent:\n once: %q\ntwice: %q", once, twice)
	}
}

// TestCRLFInput covers a file with Windows line endings: frontmatter must still
// be detected (and left verbatim), a colon intro must still be recognised, and
// the output must stay CRLF.
func TestCRLFInput(t *testing.T) {
	lf := "---\ntitle: T\ndescription: use <x> verbatim\n---\n\nFor example:\n\n\tomnictl get <id>\n"
	in := strings.ReplaceAll(lf, "\n", "\r\n")
	want := strings.ReplaceAll("---\ntitle: T\ndescription: use <x> verbatim\n---\n\nFor example:\n\n```\nomnictl get <id>\n```\n", "\n", "\r\n")
	once := string(normalizeBytes([]byte(in), false, true))
	if once != want {
		t.Errorf("CRLF input not normalized:\n got: %q\nwant: %q", once, want)
	}
	if twice := string(normalizeBytes([]byte(once), false, true)); once != twice {
		t.Errorf("CRLF pass not idempotent:\n once: %q\ntwice: %q", once, twice)
	}
	// The LF equivalent must produce the same content, modulo line endings.
	if got := string(normalizeBytes([]byte(lf), false, true)); got != strings.ReplaceAll(want, "\r\n", "\n") {
		t.Errorf("CRLF and LF results differ:\n got: %q\nwant: %q", got, strings.ReplaceAll(want, "\r\n", "\n"))
	}
}
